//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalendarzKarieryData
{
	using System;
	using System.Data.Common;
	using System.Data.Entity;
	using System.Data.Entity.Infrastructure;
    
    public partial class KalendarzKarieryDBEntities : DbContext
    {
        public KalendarzKarieryDBEntities()
            : base("name=KalendarzKarieryDBEntities")
        {
        }

		public KalendarzKarieryDBEntities(DbConnection connection)
					: base(connection, true)
					{
					}
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventKind> EventKinds { get; set; }
        public virtual DbSet<EventStatus> EventStatus { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<NoteKind> NoteKinds { get; set; }
        public virtual DbSet<PrivacyLevel> PrivacyLevels { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserAccountInfo> UserAccountInfoes { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
