//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalendarzKarieryData
{
    using System;

    public partial class Note
    {
        public int Id { get; set; }
        public string Data { get; set; }
        public int OwnerUserId { get; set; }
        public Nullable<int> NoteKindId { get; set; }
        public int PrivacyLevelId { get; set; }
        public System.DateTime DisplayDate { get; set; }
        public bool IsLineThrough { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual NoteKind NoteKind { get; set; }
        public virtual PrivacyLevel PrivacyLevel { get; set; }
        public virtual User User { get; set; }
    }
}
