//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalendarzKarieryData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Addresses = new HashSet<Address>();
            this.Comments = new HashSet<Comment>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Details { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int OwnerUserId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<int> OccupancyLimit { get; set; }
        public string UrlLink { get; set; }
        public int EventKindId { get; set; }
        public Nullable<int> NumberOfPeopleAttending { get; set; }
        public int PrivacyLevelId { get; set; }
        public int EventStatusId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual EventKind EventKind { get; set; }
        public virtual EventStatus EventStatus { get; set; }
        public virtual User User { get; set; }
        public virtual PrivacyLevel PrivacyLevel { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
